name: just testing something

on: workflow_dispatch

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop'
        
        steps:

            -   name: Build with Gradle
                run: echo "Hello from test :D"